- name: APT | Repository Konfiguration
  template: src=apt/sources.list dest=/etc/apt/sources.list
  when: ansible_machine != "armv6l" and ansible_machine != "armv7l" and ansible_distribution == 'Debian'

- name: APT | automatic apt-get update
  copy: src=apt/90-custom dest=/etc/apt/apt.conf.d/90-custom

- name: apt update
  apt:
    autoclean: yes
    autoremove: yes
    upgrade: dist
