- name: "deploy ssh_keys for every user"
  template:
    src: "ssh_keys"
    dest: "{{ item.homedir }}.ssh/authorized_keys"
    mode: 0600
    owner: "{{ item.name }}"
    group: root
  with_items:
    - "{{ common.users }}"

- name: "ssh_config"
  template:
    src: "ssh_config"
    dest: "/etc/ssh/ssh_config"
    mode: 0644
    owner: root
    group: root

- name: "sshd_config"
  template:
    src: "sshd_config"
    dest: "/etc/ssh/sshd_config"
    mode: 0644
    owner: root
    group: root
  notify: "linux_restart_sshd"
