
- name: Bash | .profile verteilen
  copy: src=profile dest="{{ item.homedir }}.profile" mode=0644 follow=yes unsafe_writes=yes
  with_items: "{{common.users | default([])}}"

- name: Bash | .bashrc verteilen
  copy: src=bashrc dest="{{ item.homedir }}.bashrc" mode=0644 follow=yes unsafe_writes=yes
  with_items: "{{common.users | default([])}}"

- name: vim | .vimrc verteilen
  copy: src=vimrc dest="{{ item.homedir }}.vimrc" mode=0644 follow=yes unsafe_writes=yes
  with_items: "{{common.users | default([])}}"

- name: copy user scripts
  copy: src={{item}} dest="/usr/bin/" mode=0755
  with_items:
    - waitpid

- include_tasks: portage.yml
  when: ansible_distribution == 'Gentoo'

- include_tasks: apt.yml
  when: ansible_os_family == 'Debian'

- include_tasks: pacman.yml
  when: ansible_os_family == 'Archlinux'
  tags:
    - update
    - upgrade

- name: copy xinetd check_mk
  copy: src=xinet-check_mk dest="/etc/xinetd.d/check_mk" mode=644
  tags: checkmk
  notify:
    - restart xinetd

- name: enable xinetd
  service: enabled=yes name=xinetd
